---
name: Publish Gem

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: bundle install

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Build package gem
        run: bundle exec rake gem:package

      - name: Configure Trusted Publisher
        uses: rubygems/configure-rubygems-credentials@v1.0.0

      - name: Publish Gem
        run: gem push pkg/*.gem
