---
name: Publish Gem

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            name: windows
            path: "ext/libext.dll"
          - os: ubuntu-latest
            name: linux
            path: "ext/libext.so"
          - os: macos-latest
            name: macos
            path: "ext/libext.dylib"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Build extension
        run: bundle exec rake gem:build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-${{ matrix.name }}
          path: ${{ matrix.path }}

  Publish:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Download build linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-linux
          path: ext/libext.so

      - name: Download build windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-windows
          path: ext/libext.dll

      - name: Download build macos artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-macos
          path: ext/libext.dylib

      - name: Configure RubyGems Credentials
        uses: rubygems/configure-rubygems-credentials@main
        with:
          role-to-assume: rg_oidc_akr_f55fe1127adjkkcn8ty6

      - name: Publish Gem
        uses: rubygems/release-gem@v1
